name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    name: Lint and Build Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run Expo Lint
      run: npm run lint
      continue-on-error: true
    
    - name: Verify critical files
      run: |
        echo "Checking critical files..."
        test -f "App.js" && echo "✅ App.js exists"
        test -f "package.json" && echo "✅ package.json exists"
        test -d "screens" && echo "✅ screens directory exists"
        test -d "navigation" && echo "✅ navigation directory exists"
    
    - name: Check JavaScript syntax
      run: |
        echo "Validating JavaScript syntax..."
        node --check App.js
        echo "✅ No syntax errors found!"
    
    - name: Build status
      run: echo "🎉 Frontend validation completed successfully!"